### ISSUE TITLE
migrationsDir should accept relative path

### ISSUE THREAD

**Issue by mrfelton** [fullcube/loopback-component-migrate#9]
Currently, migrationsDir expects an absolute path (even though the default value of server/migrations is relative). Path should be relative to the application root.

**Comment by gijo-varghese** [comment]
@mrfelton is this fixed? For me its generating in the root folder. Not inside server.

my config:
```
"loopback-component-migrate": {
    "dataSource": "postgres",
    "migrationsDir": "server/migrations"
  }
```
